services:
  gateway:
    restart: unless-stopped
    networks:
      - gala_services_net
    image: envoyproxy/envoy:v1.11.1
    ports:
      - "5000:80"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
  
  dynamo-packages:
    restart: unless-stopped
    networks:
      - gala_services_net
    depends_on:
      - postgresql
      - redis
      - seq
    env_file:
      - .env
    image: ${DOCKER_REGISTRY-}gala_dynamo_packages
    build:
      context: .
      dockerfile: GalaFamilyLibrary.DynamoPackageService/Dockerfile
  
  family-library:
    restart: unless-stopped
    networks:
      - gala_services_net
    depends_on:
      - postgresql
      - redis
      - seq
    env_file:
      - .env
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro      
    image: ${DOCKER_REGISTRY-}gala_family_library
    build:
      context: .
      dockerfile: GalaFamilyLibrary.FamilyService/Dockerfile

  identity:
    restart: on-failure
    networks:
      - gala_services_net
    depends_on:
      - postgresql
      - redis
      - seq
    env_file:
      - .env
    image: ${DOCKER_REGISTRY-}gala_identity
    build:
      context: .
      dockerfile: GalaFamilyLibrary.IdentityService/Dockerfile
  
  family-parameters:
    env_file:
      - .env
    restart: on-failure
    networks:
      - gala_services_net
    depends_on:
      - postgresql
      - redis
      - seq
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    image: ${DOCKER_REGISTRY-}gala_family_parameters
    build:
      context: .
      dockerfile: GalaFamilyLibrary.ParameterService/Dockerfile

  postgresql:
    networks:
      - gala_services_net
    restart: unless-stopped
    image: postgres
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERID}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
      TZ: "GMT+8"
      PGTZ: "GMT+8"      

  redis:
    networks:
      - gala_services_net
    restart: unless-stopped
    image: "redis"
    ports:
      - "${REDIS_PORT}:6379"
    command:
      redis-server --requirepass ${REDIS_PASSWORD}

  seqcli:
    image: datalust/seqcli:latest
    command: apikey create -t newapikey --token ${SEQ_APIKEY} -s http://seq
    depends_on:
      - seq
    restart: on-failure:5
    networks:
      - gala_services_net
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQ_ADMINPASSWORD}
    ports:
      - "5341:80"
    networks:
      - gala_services_net

networks:
  gala_services_net:
    driver: bridge

