version: '3.4'

services:
  library_gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

  dynamo_package:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
  
  
  family_library:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
  
  
  library_identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging 