version: '3.4'

services:
  library_gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  dynamo_package:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  
  family_library:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


  library_identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


  file_storage:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FILE_STORAGE_KEY=cf940b17-4ab8-d540-1ee5-a781c741e5ee
  
  redis:
    command:
      redis-server --requirepass $REDIS_PASSWORD
  
  postgresql:
    environment:
      POSTGRES_USER: $DATABASE_USERID
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_DATABASE
      
      
  gala_services_parameters:
    image: ${DOCKER_REGISTRY-}gala_services_parameters
    build:
      context: .
      dockerfile: GalaFamilyLibrary.ParameterService/Dockerfile

