version: '3.4'

services:
  library_gateway:
    restart: on-failure
    container_name: "library_gateway"
    networks:
      - "family_library"
    image: envoyproxy/envoy:v1.11.1
    ports:
      - "5000:80"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
  
  dynamo_package:
    container_name: "dynamo_package"
    restart: on-failure
    networks:
      - "family_library"
    depends_on:
      - postgresql
      - redis
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_DATABASE=$DATABASE_DATABASE
      - DATABASE_USERID=$DATABASE_USERID
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - REDIS_HOST=$REDIS_HOST,
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - AUDIENCE_ISSUER=$AUDIENCE_ISSUER
      - AUDIENCE_AUDIENCE=$AUDIENCE_AUDIENCE
      - AUDIENCE_KEY=$AUDIENCE_KEY
      - AUDIENCE_EXPIRATION=$AUDIENCE_EXPIRATION
      - TZ=$TIMEZONE

    image: dynamo_package
    build:
      context: .
      dockerfile: GalaFamilyLibrary.DynamoPackageService/Dockerfile
  
  family_library:
    container_name: "family_library"
    restart: on-failure
    networks:
      - "family_library"
    depends_on:
      - postgresql
      - redis
    ports:
      - "6001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_DATABASE=$DATABASE_DATABASE
      - DATABASE_USERID=$DATABASE_USERID
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - REDIS_HOST=$REDIS_HOST,
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - AUDIENCE_ISSUER=$AUDIENCE_ISSUER
      - AUDIENCE_AUDIENCE=$AUDIENCE_AUDIENCE
      - AUDIENCE_KEY=$AUDIENCE_KEY
      - AUDIENCE_EXPIRATION=$AUDIENCE_EXPIRATION
      - TZ=$TIMEZONE

    image: family_library
    build:
      context: .
      dockerfile: GalaFamilyLibrary.FamilyService/Dockerfile

  library_identity:
    container_name: "library_identity"
    restart: on-failure
    networks:
      - "family_library"
    depends_on:
      - postgresql
      - redis
    ports:
      - "7001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_DATABASE=$DATABASE_DATABASE
      - DATABASE_USERID=$DATABASE_USERID
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - REDIS_HOST=$REDIS_HOST,
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - AUDIENCE_ISSUER=$AUDIENCE_ISSUER
      - AUDIENCE_AUDIENCE=$AUDIENCE_AUDIENCE
      - AUDIENCE_KEY=$AUDIENCE_KEY
      - AUDIENCE_EXPIRATION=$AUDIENCE_EXPIRATION
      - TZ=$TIMEZONE

    image: library_identity
    build:
      context: .
      dockerfile: GalaFamilyLibrary.IdentityService/Dockerfile

  file_storage:
    container_name: "file_storage"
    restart: on-failure
    ports:
      - "8001:80"
    networks:
      - family_library
    image: file_storage
    build:
      context: .
      dockerfile: GalaFamilyLibrary.FileStorageService/Dockerfile
  
  gala_services_parameters:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro    

  postgresql:
    networks:
      - "family_library"
    restart: always
    image: postgres
    container_name: "postgresql"
    ports:
      - "$DATABASE_PORT:5432"
    environment:
      POSTGRES_USER: $DATABASE_USERID
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_DATABASE

  redis:
    networks:
      - "family_library"
    restart: always
    container_name: "redis"
    image: "redis"
    ports:
      - "$REDIS_PORT:6379"
    command:
      redis-server --requirepass $REDIS_PASSWORD

  seqcli:
    image: datalust/seqcli:latest
    container_name: "seqcli"
    command: apikey create -t newapikey --token $SEQ_TOKEN -s http://seq
    depends_on:
      - seq
    restart: on-failure
    networks:
      - family_library
  seq:
    image: datalust/seq:latest
    container_name: "seq"
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    networks:
      - family_library


networks:
  family_library:
    driver: bridge

