version: '3.4'

services:
  library_gateway:
    restart: on-failure
    container_name: "library_gateway"
    networks:
      - "family_library"
    image: envoyproxy/envoy:v1.11.1
    ports:
      - "5000:80"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
  
  dynamo_package:
    container_name: "dynamo_package"
    networks:
      - "family_library"
    depends_on:
      - postgresql
      - redis
    ports:
      - "5001:80"
    image: dynamo_package
    build:
      context: .
      dockerfile: GalaFamilyLibrary.DynamoPackageService/Dockerfile
  
  family_library:
    container_name: "family_library"
    networks:
      - "family_library"
    depends_on:
      - postgresql
      - redis
    ports:
      - "6001:80"
    image: family_library
    build:
      context: .
      dockerfile: GalaFamilyLibrary.FamilyService/Dockerfile

  library_identity:
    container_name: "library_identity"
    networks:
      - "family_library"
    depends_on:
      - postgresql
      - redis
    ports:
      - "7001:80"
    image: library_identity
    build:
      context: .
      dockerfile: GalaFamilyLibrary.IdentityService/Dockerfile

  file_storage:
    container_name: "file_storage"
    ports:
      - "8001:80"
    networks:
      - family_library
    image: file_storage
    build:
      context: .
      dockerfile: GalaFamilyLibrary.FileStorageService/Dockerfile
  
  postgresql:
    networks:
      - "family_library"
    restart: always
    image: postgres
    container_name: "postgresql"
    ports:
      - "5432:5432"
  
  redis:
    networks:
      - "family_library"
    restart: always
    container_name: "redis"
    image: "redis"
    ports:
      - "6379:6379"
    command:
      redis-server --requirepass $REDIS_PASSWORD

  seqcli:
    image: datalust/seqcli:latest
    container_name: "seqcli"
    command: apikey create -t newapikey --token tZSCDVnAbyYZB1s4twSl -s http://seq
    depends_on:
      - seq
    restart: on-failure
    networks:
      - family_library
  seq:
    image: datalust/seq:latest
    container_name: "seq"
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    networks:
      - family_library

networks:
  family_library:
    driver: bridge
