version: '3.4'

services:
  library_gateway:
    container_name: "library_gateway"
    networks:
      - "family_library"
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_CONNECTION_STRING=server=mysql;port=3306;database=LibraryGateway;userid=root;password=zy4318422;CharSet=utf8mb4
      - REDIS_CONNECTION_STRING= redis,password=zy4318422
    ports:
      - "5000:80"
    image: library_gateway
    build:
      context: .
      dockerfile: GalaFamilyLibrary.Gateway/Dockerfile

  dynamo_package:
    container_name: "dynamo_package"
    networks:
      - "family_library"
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_CONNECTION_STRING=server=mysql;port=3306;database=DynamoPackage;userid=root;password=zy4318422;CharSet=utf8mb4
      - REDIS_CONNECTION_STRING= redis,password=zy4318422
    ports:
      - "5001:80"
    image: dynamo_package
    build:
      context: .
      dockerfile: GalaFamilyLibrary.DynamoPackageService/Dockerfile
  
  family_library:
    container_name: "family_library"
    networks:
      - "family_library"
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_CONNECTION_STRING=server=mysql;port=3306;database=FamilyLibrary;userid=root;password=zy4318422;CharSet=utf8mb4
      - REDIS_CONNECTION_STRING= redis,password=zy4318422
    ports:
      - "5002:80"
    
    image: family_library
    build:
      context: .
      dockerfile: GalaFamilyLibrary.FamilyService/Dockerfile

  library_identity:
    container_name: "library_identity"
    networks:
      - "family_library"
    depends_on:
      - mysql
      - redis
    environment:
      #     - ASPNETCORE_URLS=https:http://+:80
      - DATABASE_CONNECTION_STRING=server=mysql;port=3306;database=LibraryUser;userid=root;password=zy4318422;CharSet=utf8mb4
      - REDIS_CONNECTION_STRING= redis,password=zy4318422
    ports:
      - "5003:80"
    image: library_identity
    build:
      context: .
      dockerfile: GalaFamilyLibrary.IdentityService/Dockerfile
  
  mysql:
    networks:
      - "family_library"
    restart: always
    image: "mysql"
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: zy4318422
    ports:
      - "3306:3306"
  
  redis:
    networks:
      - "family_library"
    restart: always
    container_name: "redis"
    image: "redis"
    ports:
      - "6379:6379"
    command: redis-server --requirepass zy4318422
  seqcli:
    image: datalust/seqcli:latest
    container_name: "seqcli"
    command: apikey create -t newapikey --token tZSCDVnAbyYZB1s4twSl -s http://seq
    depends_on:
      - seq
    restart: on-failure
    networks:
      - family_library
  seq:
    image: datalust/seq:latest
    container_name: "seq"
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    networks:
      - family_library
networks:
  family_library:
    driver: bridge