version: '3.4'

services:
  library_gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
  dynamo_package:
    environment:
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_DATABASE=$DATABASE_DATABASE
      - DATABASE_USERID=$DATABASE_USERID
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - REDIS_HOST=$REDIS_HOST,
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - AUDIENCE_ISSUER=$AUDIENCE_ISSUER
      - AUDIENCE_AUDIENCE=$AUDIENCE_AUDIENCE
      - AUDIENCE_KEY=$AUDIENCE_KEY
      - AUDIENCE_EXPIRATION=$AUDIENCE_EXPIRATION
      - TZ=$TIMEZONE
  
  family_library:
    environment:
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_DATABASE=$DATABASE_DATABASE
      - DATABASE_USERID=$DATABASE_USERID
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - REDIS_HOST=$REDIS_HOST,
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - AUDIENCE_ISSUER=$AUDIENCE_ISSUER
      - AUDIENCE_AUDIENCE=$AUDIENCE_AUDIENCE
      - AUDIENCE_KEY=$AUDIENCE_KEY
      - AUDIENCE_EXPIRATION=$AUDIENCE_EXPIRATION
      - TZ=$TIMEZONE

  library_identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_DATABASE=$DATABASE_DATABASE
      - DATABASE_USERID=$DATABASE_USERID
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - REDIS_HOST=$REDIS_HOST,
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - AUDIENCE_ISSUER=$AUDIENCE_ISSUER
      - AUDIENCE_AUDIENCE=$AUDIENCE_AUDIENCE
      - AUDIENCE_KEY=$AUDIENCE_KEY
      - AUDIENCE_EXPIRATION=$AUDIENCE_EXPIRATION
      - TZ=$TIMEZONE

  file_storage:
    environment:
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - FILE_STORAGE_KEY=cf940b17-4ab8-d540-1ee5-a781c741e5ee
  
  redis:
    command:
      redis-server --requirepass $REDIS_PASSWORD
  
  postgresql:
    environment:
      POSTGRES_USER: $DATABASE_USERID
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_DATABASE
      
      

