version: '3.4'

services:
  library_gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  dynamo_package:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  
  family_library:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  
  library_identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 